[project]
name = "one-article-submission"
version = "0.1.0"
description = "A multi-platform article publishing web tool."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv~=0.9.9",
    "drissionpage==4.1.0.14",
    "fastapi~=0.115.11",
    "httpx==0.27.2",
    "jinja2>=3.1.6",
    "markdown2==2.5.1",
    "mcp>=1.11.0",
    "openpyxl~=3.1.5",
    "psutil~=7.0.0",
    "pydantic~=2.8.2",
    "pyperclip~=1.9.0",
    "pypinyin==0.53.0",
    "python-dotenv~=1.0.1",
    "python-multipart>=0.0.20",
    "requests==2.32.3",
    "tenacity~=9.0.0",
    "uvicorn~=0.30.6",
    "websocket-client~=1.8.0",
]
